In [5]:
import pandas as pd
import numpy as np

df_instrumentos = pd.read_csv("lista_instrumentos.csv", low_memory=False)
display(df_instrumentos)

df_vendas = pd.read_csv("vendas_tech.csv", low_memory=False)
display(df_vendas)

df_gerentes =  pd.read_excel("gerentes_lojas.xlsx")
display(df_gerentes)

,INSTRUMENTO,NÚMERO DO TERMO,TERMO DE COLABORAÇÃO,VALOR DO PLANO DE TRABALHO,DATA CELEBRAÇÃO,VIGÊNCIA,STATUS
0,1405863,68/2025,ESPAÇO DE VIDA ARTE EDUCAÇÃO - CASA CIVIL,"R$ 200.000,00",04/11/2025,12/04/2026,EM EXECUÇÃO - NORMAL
1,1404986,28/2025,ABC SERRINHA,"R$ 945.776,40",03/11/2025,31/10/2026,EM EXECUÇÃO - NORMAL
2,1404999,27/2025,ABC CAJUEIRO TORTO,"R$ 945.776,40",03/11/2025,31/10/2026,EM EXECUÇÃO - NORMAL
3,1404996,34/2025,ABC MONDUBIM,"R$ 945.776,40",03/11/2025,31/10/2026,EM EXECUÇÃO - NORMAL
4,1378187,22/2025,CRIANÇA FELIZ,"R$ 1.300.000,00",25/06/2025,30/06/2026,EM EXECUÇÃO - NORMAL
5,1363330,15/2025,ACOLHIMENTO 02 FORTALEZA,"R$ 1.535.569,05",27/03/2025,30/11/2026,EM EXECUÇÃO - NORMAL
6,1356831,01/2025,ESPAÇO SOCIAL DIAS MACEDO,"R$ 1.297.581,01",08/01/2025,31/12/2025,EM EXECUÇÃO - NORMAL
7,1247749,25/2022,COMPLEXO SOCIAL MAIS INFÂNCIA CURIÓ,"R$ 8.333.096,60",30/11/2022,31/12/2025,EM EXECUÇÃO - NORMAL
8,1238489,12/2022,CREAS CARIRI FORTALEZA,"R$ 13.774.813,32",05/10/2022,31/12/2026,EM EXECUÇÃO - NORMAL
9,1238520,11/2022,GESTÃO,"R$ 11.402.710,68",04/10/2022,31/12/2026,EM EXECUÇÃO - NORMAL
10,1220963,10/2022,CREAS JAGUARIBE,"R$ 5.097.846,55",24/06/2022,31/12/2026,EM EXECUÇÃO - NORMAL
11,1202581,02/2022,COMPLEXO SOCIAL MAIS INFÂNCIA BARBALHA,"R$ 11.719.910,16",14/03/2022,31/12/2025,EM EXECUÇÃO - NORMAL
12,1190123,06/2021,COMPLEXO SOCIAL MAIS INFÂNCIA CRISTO REDENTOR,"R$ 11.615.533,35",04/11/2021,31/12/2025,EM EXECUÇÃO - NORMAL

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

             Loja   Gerente  Meta_Mensal
0       São Paulo    Carlos        50000
1  Rio de Janeiro  Fernanda        60000
2        Curitiba   Roberto        45000
3  Belo Horizonte   Juliana        55000
4          Recife    Marcos        48000
5    Porto Alegre     Pedro        42000
6        Salvador       Ana        52000

In [13]:
#inspeções
display(df_vendas)
#display(df_vendas.head(15))
#display(df_vendas.tail(15))
#display(df_vendas.sample(15))
display(df_vendas.shape)
display(list(df_vendas.columns))
display(df_vendas.info())
display(df_vendas.describe())

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

(100100, 8)

['ID_Pedido',
 'Data',
 'Loja',
 'Produto',
 'Preco_Unitario',
 'Qtd',
 'Cliente',
 'Data_Base']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100100 entries, 0 to 100099
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100100 non-null  int64
 1   Data            100100 non-null  object
 2   Loja            98099 non-null   object
 3   Produto         100100 non-null  object
 4   Preco_Unitario  100100 non-null  float64
 5   Qtd             100100 non-null  int64
 6   Cliente         100100 non-null  object
 7   Data_Base       1 non-null       object
dtypes: float64(1), int64(2), object(5)
memory usage: 6.1+ MB

None

           ID_Pedido  Preco_Unitario            Qtd
count  100100.000000   100100.000000  100100.000000
mean    50004.810180     2000.204595       1.499101
std     28866.872543     1841.050733       1.241605
min         1.000000       40.000000       1.000000
25%     25008.750000      120.000000       1.000000
50%     50004.500000     1200.000000       1.000000
75%     75002.250000     3200.000000       1.000000
max    100000.000000     5500.000000      10.000000